import React from 'react'
import { Row, Col } from 'react-bootstrap'
import Section from './../body/Section';


export default function HomeApplication() {
    return (
        <Section classNames={["bg-img"]}>
            <Row>
                <Col>
                    <h2 className="heading text-center">APPLICATION</h2>
                </Col>
            </Row>
            <Row>
                <Col>
                    <p className="text-center">The Ultra dB low-noise indoor sewage system is intended for the construction of non-pressure low-noise  sanitary,  storm  water  and  process  waste  water  systems.  It  is  used  for  draining  highly aggressive  domestic,  municipal  and  industrial  types  of  sewage  (2–12 pH),  including  ones characterised by a high concentration of hydrogen sulphide and, further, a high temperature. Due to its benefits, the Ultra dB system has a wide range of applications, for instance in single- and multi-family residential housing, in low and high buildings; it is also used in the systems installed in: luxury apartment buildings, nursing homes, offices, doctors’ surgeries, hotels, restaurants, hospitals, operating rooms, spas, laboratories, dentists’ surgeries, schools, lecture halls at tertiary education institutions, reading rooms, radio and TV studios, concert and conference halls, theatres, shop floors and in order to drain effluent generated by – including but not limited to – the pharmaceutical, food and catering industries (rinsing the pipes with water heated to 70°C is recommended while draining fat-laden effluent).

                    </p>
                    <img className="m-auto my-img rounded" src="./images/application.png" alt="" />
                    <br />
                    <p>The system is also perfectly suitable for draining storm water using systems installed inside the building structure.The Ultra dB system has the BD designation, which indicates that the pipes and fittings can be used not only inside the building, but also fixed onto the external walls of the building and buried in the ground within the building structure.The installation of the Ultra dB system in the BD application area is also permissible at a temperature below -20°C, which is indicated by the graphic sign (ice crystal  symbol) printed  on  the  pipes  that  meet  the  applicable  requirements  of  PN-EN  ISO 11173: 2017-12. The Ultra dB pipes and fittings can also be used wherever the temperature of sewage does not exceed +90°C (permanent flow) or +95°C (temporary flow).</p>

                </Col>
            </Row>

        </Section>
    )
}
